# Generated by Django 5.1.3 on 2025-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_author_alter_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
