# Generated by Django 5.1.3 on 2025-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='avatars/'),
        ),
    ]
